/**
 * Master list of all Hessian animal shelters covered by PetBridge.
 *
 * Fields:
 *  id         – unique slug used as stableId prefix and cache key
 *  name       – official shelter name
 *  city       – short city name (used in FilterBar / dog cards)
 *  district   – Landkreis / kreisfreie Stadt
 *  scraper    – 'specific' = has own scraper file, 'generic' = Jina generic
 *  url        – direct dog-listing URL fed to the scraper
 *  phone      – public phone number (empty string if unknown)
 *  email      – public e-mail (empty string if unknown)
 *  shelterUrl – shelter homepage
 *  wikiTitle  – German Wikipedia article title for city thumbnail (de.wikipedia.org)
 *  emoji      – fallback emoji when no wiki thumbnail is available
 *  color      – Tailwind gradient classes for UI cards (fallback bg)
 */

export const ALL_SHELTERS = [
  // ─────────────────────────────────────────────────────────────────────────
  // Specific scrapers (individual parser for each site)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'babenhausen',
    name: 'Tierheim Babenhausen',
    city: 'Babenhausen',
    district: 'Darmstadt-Dieburg',
    scraper: 'specific',
    url: 'https://www.tierheim-babenhausen-hessen.de/tiere/hunde/',
    phone: '06073 / 72 37 1',
    email: 'info@tierheim-babenhausen-hessen.de',
    shelterUrl: 'https://www.tierheim-babenhausen-hessen.de',
    wikiTitle: 'Babenhausen_(Hessen)',
    emoji: '🏡',
    color: 'from-indigo-500 to-violet-600',
  },
  {
    id: 'gelnhausen',
    name: 'Tierheim Gelnhausen',
    city: 'Gelnhausen',
    district: 'Main-Kinzig-Kreis',
    scraper: 'specific',
    url: 'https://tierheim-gelnhausen.org/hunde/',
    phone: '06051 / 25 50',
    email: 'webmaster@tierheim-gelnhausen.de',
    shelterUrl: 'https://tierheim-gelnhausen.org',
    wikiTitle: 'Gelnhausen',
    emoji: '🌿',
    color: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'hanau',
    name: 'Tierschutz Hanau',
    city: 'Hanau',
    district: 'Main-Kinzig-Kreis',
    scraper: 'specific',
    url: 'https://www.tierschutz-hanau.de/tiere/hunde-tierheim.html',
    phone: '06181 / 92 12 35',
    email: 'info@tierschutz-hanau.de',
    shelterUrl: 'https://www.tierschutz-hanau.de',
    wikiTitle: 'Hanau',
    emoji: '🌻',
    color: 'from-amber-500 to-orange-600',
  },
  {
    id: 'darmstadt',
    name: 'TSV Darmstadt',
    city: 'Darmstadt',
    district: 'Darmstadt',
    scraper: 'specific',
    url: 'https://www.tsv-darmstadt.de/hunde',
    phone: '06151 / 97 21 20',
    email: 'info@tsv-darmstadt.de',
    shelterUrl: 'https://www.tsv-darmstadt.de',
    wikiTitle: 'Darmstadt',
    emoji: '💜',
    color: 'from-rose-500 to-pink-600',
  },

  {
    id: 'koblenz',
    name: 'Tierheim Koblenz',
    city: 'Koblenz',
    district: 'Koblenz',
    scraper: 'specific',
    url: 'https://www.tierheim-koblenz.de/unsere-tiere/hunde',
    phone: '0261/40638-0',
    email: 'info@tierheim-koblenz.de',
    shelterUrl: 'https://www.tierheim-koblenz.de',
    wikiTitle: 'Koblenz',
    emoji: '🏰',
    color: 'from-red-600 to-rose-700',
  },
  {
    id: 'tsv-giessen',
    name: 'TSV Gießen',
    city: 'Gießen (TSV)',
    district: 'Gießen',
    scraper: 'specific',
    url: 'https://tsv-giessen.de/?paged=1&product_cat=hunde',
    phone: '',
    email: '',
    shelterUrl: 'https://tsv-giessen.de',
    wikiTitle: 'Gießen',
    emoji: '🌱',
    color: 'from-green-600 to-lime-600',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Generic Jina-based scrapers (all remaining Hessian shelters)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'tsv-frankfurt',
    name: 'Tierschutzverein Frankfurt e.V.',
    city: 'Frankfurt',
    district: 'Frankfurt am Main',
    scraper: 'specific',
    url: 'https://www.tsv-frankfurt.de',
    phone: '069 / 42 30 05',
    email: 'vermittlung-hunde@tsv-frankfurt.de',
    shelterUrl: 'https://www.tsv-frankfurt.de',
    wikiTitle: 'Frankfurt_am_Main',
    emoji: '🌆',
    color: 'from-red-500 to-orange-500',
  },
  {
    id: 'wiesbaden',
    name: 'Tierschutzverein Wiesbaden',
    city: 'Wiesbaden',
    district: 'Wiesbaden',
    scraper: 'generic',
    url: 'https://www.tierschutz-wiesbaden.de/tiere/hunde/',
    phone: '0611 / 99 75 22 0',
    email: 'info@tierschutz-wiesbaden.de',
    shelterUrl: 'https://www.tierschutz-wiesbaden.de',
    wikiTitle: 'Wiesbaden',
    emoji: '🏛️',
    color: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'kassel',
    name: 'Tierheim Kassel',
    city: 'Kassel',
    district: 'Kassel',
    scraper: 'generic',
    url: 'https://www.tierheim-kassel.de/unsere-tiere/hunde/',
    phone: '0561 / 28 70 06',
    email: 'info@tierheim-kassel.de',
    shelterUrl: 'https://www.tierheim-kassel.de',
    wikiTitle: 'Kassel',
    emoji: '🏰',
    color: 'from-purple-500 to-indigo-600',
  },
  {
    id: 'offenbach',
    name: 'Tierschutzverein Offenbach',
    city: 'Offenbach',
    district: 'Offenbach am Main',
    scraper: 'generic',
    url: 'https://www.tierheim-offenbach.de/unsere-tiere/hunde/',
    phone: '069 / 85 70 56',
    email: 'info@tierheim-offenbach.de',
    shelterUrl: 'https://www.tierheim-offenbach.de',
    wikiTitle: 'Offenbach_am_Main',
    emoji: '🏭',
    color: 'from-cyan-500 to-blue-600',
  },
  {
    id: 'marburg',
    name: 'Tierheim Marburg',
    city: 'Marburg',
    district: 'Marburg-Biedenkopf',
    scraper: 'generic',
    url: 'https://www.tierheim-marburg.de/tiere/hunde/',
    phone: '06421 / 16 57 0',
    email: 'info@tierheim-marburg.de',
    shelterUrl: 'https://www.tierheim-marburg.de',
    wikiTitle: 'Marburg',
    emoji: '🎓',
    color: 'from-amber-600 to-yellow-500',
  },
  {
    id: 'fulda',
    name: 'Tierheim Fulda',
    city: 'Fulda',
    district: 'Fulda',
    scraper: 'generic',
    url: 'https://www.tierheim-fulda.de/hunde/',
    phone: '0661 / 72 80 55',
    email: 'info@tierheim-fulda.de',
    shelterUrl: 'https://www.tierheim-fulda.de',
    wikiTitle: 'Fulda',
    emoji: '⛪',
    color: 'from-green-500 to-emerald-600',
  },
  {
    id: 'giessen',
    name: 'Tierschutzverein Gießen',
    city: 'Gießen',
    district: 'Gießen',
    scraper: 'generic',
    url: 'https://www.tierschutzverein-giessen.de/hunde/',
    phone: '0641 / 95 39 11',
    email: 'info@tierschutzverein-giessen.de',
    shelterUrl: 'https://www.tierschutzverein-giessen.de',
    wikiTitle: 'Gießen',
    emoji: '🌱',
    color: 'from-teal-500 to-cyan-600',
  },
  {
    id: 'limburg',
    name: 'Tierheim Limburg-Weilburg',
    city: 'Limburg',
    district: 'Limburg-Weilburg',
    scraper: 'generic',
    url: 'https://www.tierheim-limburg.de/hunde/',
    phone: '06431 / 91 15 15',
    email: 'info@tierheim-limburg.de',
    shelterUrl: 'https://www.tierheim-limburg.de',
    wikiTitle: 'Limburg_an_der_Lahn',
    emoji: '🏙️',
    color: 'from-violet-500 to-purple-600',
  },
  {
    id: 'wetzlar',
    name: 'Tierheim Lahn-Dill',
    city: 'Wetzlar',
    district: 'Lahn-Dill-Kreis',
    scraper: 'specific',
    url: 'https://tierheim-wetzlar.de/category/tiere/hunde/',
    phone: '06441 / 45 15 0',
    email: 'info@tierheim-wetzlar.de',
    shelterUrl: 'https://tierheim-wetzlar.de',
    wikiTitle: 'Wetzlar',
    emoji: '🌊',
    color: 'from-sky-500 to-blue-600',
  },
  {
    id: 'badhomburg',
    name: 'Tierheim Hochtaunus',
    city: 'Bad Homburg',
    district: 'Hochtaunuskreis',
    scraper: 'generic',
    url: 'https://www.tierheim-bad-homburg.de/hunde/',
    phone: '06172 / 92 55 05',
    email: 'info@tierheim-bad-homburg.de',
    shelterUrl: 'https://www.tierheim-bad-homburg.de',
    wikiTitle: 'Bad_Homburg_vor_der_Höhe',
    emoji: '⛰️',
    color: 'from-lime-500 to-green-600',
  },
  {
    id: 'bensheim',
    name: 'Tierschutz Bergstraße',
    city: 'Bensheim',
    district: 'Bergstraße',
    scraper: 'generic',
    url: 'https://www.tierschutz-bensheim.de/hunde/',
    phone: '06251 / 74 65',
    email: 'info@tierschutz-bensheim.de',
    shelterUrl: 'https://www.tierschutz-bensheim.de',
    wikiTitle: 'Bensheim',
    emoji: '🌲',
    color: 'from-orange-500 to-red-500',
  },
  {
    id: 'korbach',
    name: 'Tierheim Korbach',
    city: 'Korbach',
    district: 'Waldeck-Frankenberg',
    scraper: 'generic',
    url: 'https://www.tierheim-korbach.de/hunde/',
    phone: '05631 / 50 26 0',
    email: 'info@tierheim-korbach.de',
    shelterUrl: 'https://www.tierheim-korbach.de',
    wikiTitle: 'Korbach',
    emoji: '🏔️',
    color: 'from-stone-500 to-gray-600',
  },
  {
    id: 'friedberg',
    name: 'Tierheim Wetterau',
    city: 'Friedberg',
    district: 'Wetteraukreis',
    scraper: 'generic',
    url: 'https://www.tierschutzverein-wetterau.de/hunde/',
    phone: '06031 / 68 18 0',
    email: 'info@tierschutzverein-wetterau.de',
    shelterUrl: 'https://www.tierschutzverein-wetterau.de',
    wikiTitle: 'Friedberg_(Hessen)',
    emoji: '🌾',
    color: 'from-yellow-500 to-amber-600',
  },
  {
    id: 'badnauheim',
    name: 'Tierheim Bad Nauheim',
    city: 'Bad Nauheim',
    district: 'Wetteraukreis',
    scraper: 'generic',
    url: 'https://www.tierheim-bad-nauheim.de/hunde/',
    phone: '06032 / 92 73 0',
    email: 'info@tierheim-bad-nauheim.de',
    shelterUrl: 'https://www.tierheim-bad-nauheim.de',
    wikiTitle: 'Bad_Nauheim',
    emoji: '💧',
    color: 'from-sky-400 to-cyan-500',
  },
  {
    id: 'badvilbel',
    name: 'Tierheim Bad Vilbel',
    city: 'Bad Vilbel',
    district: 'Wetteraukreis',
    scraper: 'generic',
    url: 'https://www.tierheim-bad-vilbel.de/hunde/',
    phone: '06101 / 80 80 80',
    email: 'info@tierheim-bad-vilbel.de',
    shelterUrl: 'https://www.tierheim-bad-vilbel.de',
    wikiTitle: 'Bad_Vilbel',
    emoji: '🌿',
    color: 'from-green-400 to-teal-500',
  },
  {
    id: 'dietzenbach',
    name: 'Tierheim Dietzenbach',
    city: 'Dietzenbach',
    district: 'Landkreis Offenbach',
    scraper: 'generic',
    url: 'https://www.tierheim-dietzenbach.de/hunde/',
    phone: '06074 / 49 39 0',
    email: 'info@tierheim-dietzenbach.de',
    shelterUrl: 'https://www.tierheim-dietzenbach.de',
    wikiTitle: 'Dietzenbach',
    emoji: '🏠',
    color: 'from-fuchsia-500 to-violet-600',
  },
  {
    id: 'mkg',
    name: 'Tierheim Main-Kinzig',
    city: 'Schlüchtern',
    district: 'Main-Kinzig-Kreis',
    scraper: 'generic',
    url: 'https://www.tierheim-schluechtern.de/hunde/',
    phone: '06661 / 74 87',
    email: 'info@tierheim-schluechtern.de',
    shelterUrl: 'https://www.tierheim-schluechtern.de',
    wikiTitle: 'Schlüchtern',
    emoji: '🏞️',
    color: 'from-emerald-600 to-green-700',
  },
];

export const GENERIC_SHELTERS = ALL_SHELTERS.filter(s => s.scraper !== 'specific');
export const SPECIFIC_SHELTERS = ALL_SHELTERS.filter(s => s.scraper === 'specific');

/** Lookup by city name (for FilterBar population) */
export const SHELTER_BY_CITY = Object.fromEntries(ALL_SHELTERS.map(s => [s.city, s]));
